#pragma once

#include <iosfwd>
#include <memory>
#include <string>

#include <femx/assembly/AssemblyMap.hpp>
#include <femx/assembly/BoundaryMap.hpp>
#include <femx/common/Math.hpp>
#include <femx/common/Types.hpp>
#include <femx/common/Vector.hpp>
#include <femx/fem/ElementQuadData.hpp>
#include <femx/fem/FESpace.hpp>
#include <femx/fem/Mesh.hpp>
#include <femx/fem/elements/LagrangeQuadQ1.hpp>
#include <femx/inverse/LeastSquaresObjective.hpp>
#include <femx/inverse/Objective.hpp>
#include <femx/inverse/SumObjective.hpp>

namespace femx::examples::poisson_opt
{

/** @brief Configure the Poisson boundary-control optimization example. */
struct Options
{
  Index       num_x_cells = 32; ///< Number of cells in x.
  Index       num_y_cells = 32; ///< Number of cells in y.
  MemorySpace memspace =
      MemorySpace::Host;             ///< Selected memory space.
  bool  write_output       = false;  ///< Write VTU output.
  Real  alpha              = 1.0e-6; ///< Control regularization weight.
  Index observation_stride = 0;      ///< Observation spacing in mesh cells.
  Index max_iterations     = 50;     ///< Maximum TAO iterations.
};

/** @brief Report final Poisson optimization metrics. */
struct Report
{
  Real value             = 0.0; ///< Final objective value.
  Real gradient_norm     = 0.0; ///< Final reduced-gradient norm.
  Real state_rms_error   = 0.0; ///< RMS state error against the target.
  Real state_max_error   = 0.0; ///< Maximum state error against the target.
  Real control_rms_error = 0.0; ///< RMS control error against the target.
  Real control_max_error = 0.0; ///< Maximum control error against the target.
};

/** @brief Own the Poisson discretization, control layout, and objective data. */
class PoissonOptProblem
{
public:
  /**
   * @brief Construct the mesh, maps, target control, and observations.
   *
   * @param[in] opts - Validated problem options.
   */
  explicit PoissonOptProblem(const Options& opts);

  PoissonOptProblem(const PoissonOptProblem&)            = delete;
  PoissonOptProblem& operator=(const PoissonOptProblem&) = delete;
  PoissonOptProblem(PoissonOptProblem&&)                 = delete;
  PoissonOptProblem& operator=(PoissonOptProblem&&)      = delete;

  /** @brief Return the validated problem options. */
  const Options& options() const noexcept;

  /** @brief Return the finite-element mesh. */
  const fem::Mesh& mesh() const noexcept;

  /** @brief Return reusable Host element quadrature data. */
  const fem::HostElementQuadData& elementData() const noexcept;

  /** @brief Return the element assembly map. */
  const assembly::HostAssemblyMap& assemblyMap() const noexcept;

  /** @brief Return the constrained boundary rows. */
  const assembly::HostBoundaryMap& boundaryMap() const noexcept;

  /** @brief Return control state degrees of freedom in parameter order. */
  const HostVector<Index>& controlDofs() const noexcept;

  /** @brief Return the manufactured target control. */
  const HostVector<Real>& targetControl() const noexcept;

  /** @brief Return the prepared stationary objective. */
  const inverse::Objective& objective() const;

  /**
   * @brief Prepare the objective from the discrete target state.
   *
   * @param[in] target_state - State generated from `targetControl()`.
   */
  void prepareObjective(HostVector<Real> target_state);

  /** @brief Return the number of mesh nodes. */
  Index numNodes() const noexcept;

  /** @brief Return the state-vector size. */
  Index numStates() const noexcept;

  /** @brief Return the boundary-control size. */
  Index numParameters() const noexcept;

  /** @brief Return the number of observation samples. */
  Index numObservations() const noexcept;

  /**
   * @brief Compute final error and gradient metrics.
   *
   * @param[in] ctr - Optimized boundary control.
   * @param[in] state - State generated by `ctr`.
   * @param[in] val - Reduced-objective value.
   * @param[in] grad - Reduced gradient.
   * @return Final optimization metrics.
   */
  Report report(const HostVector<Real>& ctr,
                const HostVector<Real>& state,
                Real                    val,
                const HostVector<Real>& grad) const;

  /**
   * @brief Write final state and control fields to VTU.
   *
   * @param[in] ctr - Optimized boundary control.
   * @param[in] state - Final state vector.
   * @param[in] base - Output path without extension, or with `.vtu`.
   */
  void writeSolution(const HostVector<Real>& ctr,
                     const HostVector<Real>& state,
                     const std::string&      base) const;

private:
  static Real exactValue(const fem::Mesh::Node& p);

  void initBoundary();
  void initTargetControl();
  void initObservations();
  void writeFields(const HostVector<Real>& ctr,
                   const HostVector<Real>& state,
                   const std::string&      path) const;
  void writeObservations(const HostVector<Real>& state,
                         const std::string&      path) const;

  Index            effectiveObservationStride() const;
  HostVector<Real> observationWeights() const;
  bool             isBoundaryNode(const fem::Mesh::Node& p) const;
  bool             isControlNode(const fem::Mesh::Node& p) const;

  Options                  opts_;      ///< Validated options.
  fem::Mesh                mesh_;      ///< Finite-element mesh.
  fem::LagrangeQuadQ1      fe_;        ///< Scalar finite element.
  fem::FESpace             space_;     ///< Scalar finite-element space.
  fem::HostElementQuadData elem_data_; ///< Host integration data.

  assembly::HostAssemblyMap assm_map_;     ///< Element assembly mapping.
  assembly::HostBoundaryMap boundary_map_; ///< All constrained rows.

  HostVector<Index>  ctr_dofs_;     ///< Parameter-controlled rows.
  HostVector<Real>   ctr_weights_;  ///< Boundary quadrature weights.
  HostVector<Real>   target_state_; ///< Discrete target state.
  HostVector<Real>   target_ctr_;   ///< Manufactured target control.
  HostVector<Index>  obs_dofs_;     ///< Observed state entries.
  HostVector<Point3> obs_points_;   ///< Observation coordinates.

  std::unique_ptr<inverse::LeastSquaresObjective> misfit_; ///< Sparse state misfit.
  std::unique_ptr<inverse::LeastSquaresObjective> reg_;    ///< Boundary-control regularization.
  std::unique_ptr<inverse::SumObjective>          obj_;    ///< Complete objective.
};

/**
 * @brief Parse Poisson optimization command-line options.
 *
 * @param[in] argc - Argument count.
 * @param[in] argv - Argument values.
 * @param[in] ignore_unknown - Whether to ignore solver-owned options.
 * @return Parsed and validated options.
 * @throws std::runtime_error - If an option is invalid.
 */
Options parseOptions(int argc, char** argv, bool ignore_unknown);

/**
 * @brief Print command-line usage for an optimization executable.
 *
 * @param[in,out] out - Output stream.
 * @param[in] app_name - Executable name.
 * @param[in] petsc_options - Whether PETSc options are accepted.
 */
void printUsage(std::ostream& out,
                const char*   app_name,
                bool          petsc_options);

/** @brief Return the build-local directory for optimization output. */
const char* outputDir();

/**
 * @brief Return the problem-specific output file stem.
 *
 * @param[in] opts - Problem options.
 * @return Output file stem.
 */
std::string outputStem(const Options& opts);

/**
 * @brief Print the standard optimization result summary.
 *
 * @param[in,out] out - Output stream.
 * @param[in] configuration - Solver configuration name.
 * @param[in] problem - Solved optimization problem.
 * @param[in] rep - Final optimization metrics.
 * @param[in] iterations - Number of optimizer iterations.
 * @param[in] reason - PETSc/TAO convergence reason.
 */
void printReport(std::ostream&            out,
                 const std::string&       configuration,
                 const PoissonOptProblem& problem,
                 const Report&            rep,
                 Index                    iterations,
                 int                      reason);

} // namespace femx::examples::poisson_opt
