#pragma once

#include <array>
#include <map>
#include <string>
#include <utility>

#include <femx/common/Types.hpp>
#include <femx/fem/Element.hpp>
#include <femx/linalg/Vector.hpp>

namespace femx
{

/**
 * @brief Unstructured finite-element mesh with optional physical boundary data.
 *
 * Mesh stores nodal coordinates, element connectivity, and the physical names
 * imported from mesh files or generated by structured-mesh helpers.  Elements
 * own a copy of their nodal coordinates so geometry evaluation can be done
 * without looking up nodes repeatedly during assembly.
 */
class Mesh
{
public:
  using Node = Element::Node;

  /**
   * @brief Boundary facet imported from a mesh file.
   *
   * Facets are grouped by physical tag/name and can be used to impose boundary
   * conditions on named parts of the mesh.
   */
  struct BoundaryFacet
  {
    Index          dim  = 0;                        ///< Topological dimension of the facet.
    Index          etag = 0;                        ///< Element tag from the mesh file.
    Index          ptag = 0;                        ///< Physical boundary tag.
    std::string    pname;                           ///< Physical boundary name.
    Element::Shape shape = Element::Shape::Unknown; ///< Facet element shape.
    Vector<Index>  nids;                            ///< Mesh-node ids on the facet.
  };

  Mesh() = default;

  explicit Mesh(Index dim)
    : dim_(dim)
  {
  }

  /**
   * @brief Create a two-dimensional quadrilateral mesh on a rectangle.
   *
   * @param[in] num_x_cells - Number of cells in the x direction.
   * @param[in] num_y_cells - Number of cells in the y direction.
   * @param[in] x_min - Lower x coordinate.
   * @param[in] x_max - Upper x coordinate.
   * @param[in] y_min - Lower y coordinate.
   * @param[in] y_max - Upper y coordinate.
   * @return Mesh with Q1-compatible quadrilateral connectivity.
   */
  static Mesh makeStructuredQuad(Index num_x_cells,
                                 Index num_y_cells,
                                 Real  x_min = 0.0,
                                 Real  x_max = 1.0,
                                 Real  y_min = 0.0,
                                 Real  y_max = 1.0);

  Index dim() const noexcept
  {
    return dim_;
  }

  Index numNodes() const noexcept
  {
    return nodes_.size();
  }

  Index numElems() const noexcept
  {
    return elems_.size();
  }

  const Vector<Element>& elems() const noexcept
  {
    return elems_;
  }

  const Element& elem(Index ie) const
  {
    return elems_[ie];
  }

  const Vector<BoundaryFacet>& boundaryFacets() const noexcept
  {
    return boundary_facets_;
  }

  Vector<BoundaryFacet> boundaryFacets(const std::string& pname) const
  {
    Vector<BoundaryFacet> facets;
    for (const auto& facet : boundary_facets_)
    {
      if (facet.pname == pname)
      {
        facets.push_back(facet);
      }
    }
    return facets;
  }

  const std::map<std::pair<Index, Index>, std::string>&
  physicalNames() const noexcept
  {
    return physical_names_;
  }

  std::string physicalName(Index dim, Index tag) const
  {
    const auto it = physical_names_.find({dim, tag});
    if (it == physical_names_.end())
    {
      return {};
    }
    return it->second;
  }

  const Node& node(Index in) const
  {
    return nodes_[in];
  }

  const Index* elemNodeIds(Index ie) const
  {
    return elems_[ie].nodeIdsData();
  }

  void addNode(const Node& node)
  {
    nodes_.push_back(node);
  }

  /** @brief Add one element using mesh node ids. */
  void addElem(const Vector<Index>& nids)
  {
    addElem(nids, Element::Shape::Unknown, dim_, 0, 0, {});
  }

  /**
   * @brief Add one element with topology and physical classification.
   *
   * @param[in] nids - Mesh node ids in element-local order.
   * @param[in] shape - Element topology.
   * @param[in] edim - Entity dimension from the mesh generator.
   * @param[in] etag - Entity tag from the mesh generator.
   * @param[in] ptag - Physical group tag.
   * @param[in] pname - Physical group name.
   */
  void addElem(const Vector<Index>& nids,
               Element::Shape       shape,
               Index                edim,
               Index                etag,
               Index                ptag,
               std::string          pname)
  {
    Vector<Node> cn;
    cn.reserve(nids.size());
    for (Index in : nids)
    {
      cn.push_back(node(in));
    }
    elems_.emplace_back(nids,
                        std::move(cn),
                        shape,
                        edim,
                        etag,
                        ptag,
                        std::move(pname));
  }

  void addBoundaryFacet(BoundaryFacet facet)
  {
    boundary_facets_.push_back(std::move(facet));
  }

  void addPhysicalName(Index       dim,
                       Index       tag,
                       std::string name)
  {
    physical_names_[{dim, tag}] = std::move(name);
  }

private:
  Index                 dim_{0};
  Vector<Node>          nodes_;
  Vector<Element>       elems_;
  Vector<BoundaryFacet> boundary_facets_;
  std::map<std::pair<Index, Index>, std::string>
      physical_names_;
};

} // namespace femx
