#pragma once

#include <stdexcept>

#include <femx/ad/Enzyme.hpp>
#include <femx/assembly/BoundaryElementKernel.hpp>
#include <femx/common/Types.hpp>
#include <femx/linalg/DenseMatrix.hpp>
#include <femx/linalg/Vector.hpp>
#include <femx/mesh/Mesh.hpp>

namespace femx
{
namespace assembly
{

using LocalBoundaryResidualFunction = void (*)(Index       facet,
                                               Index       entity_tag,
                                               Index       physical_tag,
                                               Index       num_res,
                                               Index       num_states,
                                               Index       num_params,
                                               const Real* state,
                                               const Real* params,
                                               Real*       out);

/** @brief BoundaryElementKernel whose local Jacobians are generated by Enzyme. */
template <LocalBoundaryResidualFunction Residual>
class EnzymeBoundaryElementKernel final : public BoundaryElementKernel
{
public:
  EnzymeBoundaryElementKernel(Index num_res,
                              Index num_states,
                              Index num_params)
    : num_res_(num_res),
      num_states_(num_states),
      num_params_(num_params)
  {
    if (num_res_ < 0 || num_states_ < 0 || num_params_ < 0)
    {
      throw std::runtime_error(
          "EnzymeBoundaryElementKernel received invalid dimensions");
    }
  }

  void res(Index                       ib,
           const Mesh::BoundaryFacet& facet,
           const Vector&              u,
           const Vector&              m,
           Vector&                    out) const override
  {
    checkInputSizes(u, m);
    resize(out, num_res_);
    Residual(ib,
             facet.entity_tag,
             facet.physical_tag,
             num_res_,
             num_states_,
             num_params_,
             u.data(),
             m.data(),
             out.data());
  }

  void stateJac(Index                       ib,
                const Mesh::BoundaryFacet& facet,
                const Vector&              u,
                const Vector&              m,
                DenseMatrix&               out) const override
  {
    checkInputSizes(u, m);
    out.resize(num_res_, num_states_);

#if defined(FEMX_HAS_ENZYME)
    Vector primal_out(num_res_);
    Vector out_adj(num_res_);
    Vector state_adj(num_states_);

    for (Index row = 0; row < num_res_; ++row)
    {
      primal_out.setZero();
      out_adj.setZero();
      state_adj.setZero();
      out_adj[row] = 1.0;

      __enzyme_autodiff<void>(reinterpret_cast<void*>(Residual),
                              enzyme_const,
                              ib,
                              enzyme_const,
                              facet.entity_tag,
                              enzyme_const,
                              facet.physical_tag,
                              enzyme_const,
                              num_res_,
                              enzyme_const,
                              num_states_,
                              enzyme_const,
                              num_params_,
                              enzyme_dup,
                              u.data(),
                              state_adj.data(),
                              enzyme_const,
                              m.data(),
                              enzyme_dup,
                              primal_out.data(),
                              out_adj.data());

      for (Index col = 0; col < num_states_; ++col)
      {
        out(row, col) = state_adj[col];
      }
    }
#else
    (void) ib;
    (void) facet;
    (void) out;
    throwUnavailable();
#endif
  }

  void paramJac(Index                       ib,
                const Mesh::BoundaryFacet& facet,
                const Vector&              u,
                const Vector&              m,
                DenseMatrix&               out) const override
  {
    checkInputSizes(u, m);
    out.resize(num_res_, num_params_);

#if defined(FEMX_HAS_ENZYME)
    Vector primal_out(num_res_);
    Vector out_adj(num_res_);
    Vector param_adj(num_params_);

    for (Index row = 0; row < num_res_; ++row)
    {
      primal_out.setZero();
      out_adj.setZero();
      param_adj.setZero();
      out_adj[row] = 1.0;

      __enzyme_autodiff<void>(reinterpret_cast<void*>(Residual),
                              enzyme_const,
                              ib,
                              enzyme_const,
                              facet.entity_tag,
                              enzyme_const,
                              facet.physical_tag,
                              enzyme_const,
                              num_res_,
                              enzyme_const,
                              num_states_,
                              enzyme_const,
                              num_params_,
                              enzyme_const,
                              u.data(),
                              enzyme_dup,
                              m.data(),
                              param_adj.data(),
                              enzyme_dup,
                              primal_out.data(),
                              out_adj.data());

      for (Index col = 0; col < num_params_; ++col)
      {
        out(row, col) = param_adj[col];
      }
    }
#else
    (void) ib;
    (void) facet;
    (void) out;
    throwUnavailable();
#endif
  }

private:
  void checkInputSizes(const Vector& u, const Vector& m) const
  {
    if (u.size() != num_states_ || m.size() != num_params_)
    {
      throw std::runtime_error(
          "EnzymeBoundaryElementKernel input size mismatch");
    }
  }

  static void resize(Vector& out, Index size)
  {
    if (out.size() != size)
    {
      out.resize(size);
    }
    else
    {
      out.setZero();
    }
  }

  [[noreturn]] static void throwUnavailable()
  {
    throw std::runtime_error(
        "EnzymeBoundaryElementKernel requires FEMX_ENABLE_ENZYME=ON");
  }

private:
  Index num_res_{0};
  Index num_states_{0};
  Index num_params_{0};
};

} // namespace assembly
} // namespace femx
