"""Python interface for the femx finite-element engine."""

from ._core import __version__
from ._core import (
    DenseLinearSolver,
    EnsembleBasis,
    FluidParams,
    HostCsrLinearSolver,
    SumTimeObjective,
    TimeBlockRegularization,
    TimeDims,
    TimeIntegrator,
    TimeLeastSquaresObjective,
    TimeObjective,
    TimeObservationData,
    TimeObservationOperator,
    TimeReducedFunctional,
    TimeRegularization,
    TimeResidual,
    TimeTrajectory,
    VariableBlock,
)
from .mesh import BoundarySurface, Mesh
from .navier_stokes import (
    DirichletBC,
    InitialStateControl,
    NavierStokesModel,
    NavierStokesProblem,
    NavierStokesReducedFunctional,
    NavierStokesSolver,
    NormalVelocityControl,
    petsc_barrier,
    petsc_finalize,
    petsc_rank,
    petsc_size,
    VelocityControl,
    TaoOptimizer,
    TaoResult,
    solver_backends,
)
from .observation import GaussianObservation, VelocityObservationOperator

__all__ = [
    "BoundarySurface",
    "DenseLinearSolver",
    "DirichletBC",
    "EnsembleBasis",
    "FluidParams",
    "GaussianObservation",
    "InitialStateControl",
    "HostCsrLinearSolver",
    "Mesh",
    "NavierStokesModel",
    "NavierStokesProblem",
    "NavierStokesReducedFunctional",
    "NavierStokesSolver",
    "NormalVelocityControl",
    "petsc_barrier",
    "petsc_finalize",
    "petsc_rank",
    "petsc_size",
    "VelocityControl",
    "solver_backends",
    "SumTimeObjective",
    "TaoOptimizer",
    "TaoResult",
    "TimeBlockRegularization",
    "TimeDims",
    "TimeIntegrator",
    "TimeLeastSquaresObjective",
    "TimeObjective",
    "TimeObservationData",
    "TimeObservationOperator",
    "TimeReducedFunctional",
    "TimeRegularization",
    "TimeResidual",
    "TimeTrajectory",
    "VariableBlock",
    "VelocityObservationOperator",
    "__version__",
]
